# Generated by Django 4.1 on 2023-12-31 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flightcrewmember',
            name='crew',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.crew'),
        ),
        migrations.AddField(
            model_name='flightcrewmember',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.flight'),
        ),
        migrations.AddField(
            model_name='flight',
            name='airplane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.airplane'),
        ),
        migrations.AddField(
            model_name='flight',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.route'),
        ),
        migrations.AddField(
            model_name='airplane',
            name='airplane_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.airplanetype'),
        ),
    ]
